language: node_js
node_js:
- "10.13"
- "11.2.0"
before_install:
before_script:
  - "npm install"
  - "npm run build"
script:
  - "npm run test-with-coverage"
notifications:
emails:
  - tak@oshiire.to
on_success: always
on_failure: always
